BEGIN TRANSACTION;
INSERT INTO "scenarios" ("text") VALUES ("FREE");
INSERT INTO "scenarios" ("text") VALUES ("I think you're muted");
INSERT INTO "scenarios" ("text") VALUES ("Can you see my screen?");
INSERT INTO "scenarios" ("text") VALUES ("You're not looking at the camera");
INSERT INTO "scenarios" ("text") VALUES ("Your camera is off");
INSERT INTO "scenarios" ("text") VALUES ("Awkward silence");
INSERT INTO "scenarios" ("text") VALUES ("Am I in the right meeting?");
INSERT INTO "scenarios" ("text") VALUES ("Sorry I'm late");
INSERT INTO "scenarios" ("text") VALUES ("Um... You forgot to stop sharing");
INSERT INTO "scenarios" ("text") VALUES ("Can the person with the echo mute?");
INSERT INTO "scenarios" ("text") VALUES ("Wearing the same shirt still");
INSERT INTO "scenarios" ("text") VALUES ("Wearing pajamas still");
INSERT INTO "scenarios" ("text") VALUES ("Hi yes you have a question?");
INSERT INTO "scenarios" ("text") VALUES ("Let me just rearrange my windows");
INSERT INTO "scenarios" ("text") VALUES ("Is this too small?");
INSERT INTO "scenarios" ("text") VALUES ("Speaker is backlit");
INSERT INTO "scenarios" ("text") VALUES ("What is that in their background?");
INSERT INTO "scenarios" ("text") VALUES ("Any questions? *silence* Anyone?");
INSERT INTO "scenarios" ("text") VALUES ("Surprise cat");
INSERT INTO "scenarios" ("text") VALUES ("Surprise dog");
INSERT INTO "scenarios" ("text") VALUES ("You cut out. Say again?");
INSERT INTO "scenarios" ("text") VALUES ("Hi can you hear me now?");
INSERT INTO "scenarios" ("text") VALUES ("Sorry my computer just froze");
INSERT INTO "scenarios" ("text") VALUES ("Sorry zoom just crashed");
INSERT INTO "scenarios" ("text") VALUES ("Sorry my dog wanted out");
INSERT INTO "scenarios" ("text") VALUES ("Sorry my mom wanted in");
INSERT INTO "scenarios" ("text") VALUES ("Can you see my chat?");
INSERT INTO "scenarios" ("text") VALUES ("I'm lagging");
INSERT INTO "scenarios" ("text") VALUES ("Loud background noises");
INSERT INTO "scenarios" ("text") VALUES ("Dog ate my webcam");
INSERT INTO "scenarios" ("text") VALUES ("Zoom University");
INSERT INTO "scenarios" ("text") VALUES ("Can I share my screen?");
INSERT INTO "scenarios" ("text") VALUES ("Outside watching lecture");
INSERT INTO "scenarios" ("text") VALUES ("Stops to chew food");
INSERT INTO "scenarios" ("text") VALUES ("Sorry, I'm on mobile");
INSERT INTO "scenarios" ("text") VALUES ("I can't see chat, just interrupt me");
INSERT INTO "scenarios" ("text") VALUES ("Using my security camera as a webcam");
INSERT INTO "scenarios" ("text") VALUES ("Zoombombers");
INSERT INTO "scenarios" ("text") VALUES ("like my background?");
COMMIT;